function param = compute_controller_base_parameters
    % load truck parameters
    load('system/parameters_building');
    
    % Task 1: continuous time dynamics in state space form
    Ac = ...
    Bc = ...
    Bdc = ...
    d = ...
    
    % Task 2: discretization
    Ts = 60;
    A = ...
    B = ...
    Bd = ...
    
    % Task 3: set point computation
    b_ref = ...
    C_ref = ...
    T_sp = ...
    p_sp = ...
    
    % Task 4: constraints for delta formulation
    Pcons = building.InputConstraints;
    Tcons = building.StateConstraints;
    Ucons = ...
    Xcons = ...
    
    % put everything together
    param.A = A;
    param.B = B;
    param.Bd = Bd;
    param.d = d;
    param.b_ref = b_ref;
    param.C_ref = C_ref;
    param.T_sp = T_sp;
    param.p_sp = p_sp;
    param.Ucons = Ucons;
    param.Xcons = Xcons;
    param.Tcons = Tcons;
    param.Pcons = Pcons;
end
